export const reversePermissions = {
  "admin.category.create": "إنشاء صنف متجر جديد",
  "admin.category.update": "تحديث معلومات صنف متجر",
  "admin.category.delete": "حذف صنف متجر",
  "admin.category.all": "طلب معلومات أصناف المتاجر في الموقع",
  "admin.category.chart": "رؤية الرسم الإحصائي الخاص بأصناف المتاجر",
  "admin.role.create": "إنشاء دور جديد",
  "admin.role.update": "تحديث معلومات الأدوار",
  "admin.role.delete": "حذف دور",
  "admin.role.all": "طلب معلومات الأدوار في الموقع",
  "admin.packs.create": "إنشاء باقة جديدة",
  "admin.packs.update": "تحديث المعلومات الخاصة بالباقات",
  "admin.packs.delete": "حذف باقة",
  "admin.packs.all": "طلب معلومات الباقات في الموقع",
  "admin.packs.chart": "رؤية الرسم الإحصائي الخاص بالباقات",
  "admin.employee.create": "إنشاء حساب لموظف جديد",
  "admin.employee.update": "تحديث معلومات الموظفين",
  "admin.employee.delete": "حذف موظفين",
  "admin.employee.all": "طلب معلومات الموظفين في الموقع",
  "admin.block.create": "إنشاء نوع حظر جديد",
  "admin.block.update": "تحديث معلومات نوع الحظر",
  "admin.block.delete": "حذف نوع حظر",
  "admin.block.all": "طلب معلومات الحظورات في الموقع",
  "admin.users.block.blockUser": "حظر مستخدم ما في الموقع",
  "admin.users.block.multiUnBlock": "فك الحظر عن مستخدم ما في الموقع",
  "admin.users.block.deleteBlock": "حذف حظر من سجل الحظورات للمستخدم ",
  "admin.users.block.allBlockForUser": "رؤية سجل الحظورات الخاص بالمستخدم",
  "admin.users.block.chartUser": "رؤية الرسم الإحصائي الخاص بالمستخدم",
  "admin.users.block.information": "رؤية معلومات المستخدمين في الموقع",
  "admin.users.block.offerUser": "رؤية العروض التي كسبها المستخدم",
  "admin.users.block.informationStoreInfo": "عرض قائمة المحلات التي اشترى منها المستخدم",
  "admin.users.update": "تحديث المعلومات الخاصة بالمستخدمين",
  "admin.users.delete": "حذف مستخدم من الموقع",
  "admin.users.filterAndSearch": "طلب معلومات المستخدمين في الموقع",
  "admin.users.statisticsInfo": "رؤية المعلومات الإحصائية الخاصة بالمستخدمين",
  "admin.home.getCount": "رؤية إحصائيات عامة عن الموقع",
  "admin.home.chartUsers": "رؤية الرسم الإحصائي الخاص بعدد المستخدمين",
  "admin.home.chartStores": "رؤية الرسم الإحصائي الخاص بعدد المحلات",
  "admin.home.cityChart": "رؤية الرسم الإحصائي الخاص بالمدن",
  "admin.home.cartChart": "رؤية الرسم الإحصائي الخاص بالكروت المكتسبة",
  "admin.store.accepted.chart": "رؤية الرسم الإحصائي الخاص بالمحلات",
  "admin.store.accepted.info": "رؤية معلومات المحلات",
  "admin.store.accepted.block": "حظر الحسابات الخاصة بالمحلات",
  "admin.store.accepted.unblock": "فك الحظر عن المحلات المحظورة",
  "admin.store.accepted.deleteBlock": "حذف حظر من سجل حظورات المحل",
  "admin.store.accepted.allBlock": "عرض سجل الحظورات الخاص بالمحل",
  "admin.store.accepted.evaluationAndSpam": "رؤية التقييمات والإبلاغات عن محل ما في الموقع",
  "admin.store.accepted.packs": "رؤية سجل الاشتراكات في الباقات لمحل ما",
  "admin.store.accepted.users": "رؤية المستخدمين الذين قاموا بالشراء من محل ما",
  "admin.store.all": "طلب معلومات المحلات في الموقع",
  "admin.store.accept": "قبول طلب انضمام محل جديد",
  "admin.store.disable": "إيقاف حساب خاص بمحل في الموقع",
  "admin.store.enable": "إعادة تفعيل حساب محل موقوف",
  "admin.notification.send": "إرسال إشعارات للمستخدمين وأصحاب المحلات",
  "admin.config.update": "تحديث القيم الأساسية في الموقع",
  "admin.config.all": "رؤية القيم الأساسية في الموقع",
  "user.myOffer": "رؤية سجل العروض التي ربحها",
  "user.gift": "إهداء العرض إلى مستخدم آخر",
  "user.home": "بيانات إحصائية حول آخر العروض التي ربحها",
  "user.openBox": "فتح كرت لربح عرض جديد",
  "user.moreEvaluation": "رؤية تقييمات المحل الذي ربح منه عروض",
  "user.spamAndEvaluation": "إمكانية تقييم المحل والإبلاغ عنه",
  "manager.verifyQr": "مسح رمز ال QR عند المستخدم",
  "manager.updateStore": "تحديث المعلومات الخاصة بالمحل",
  "manager.getStoreInfo": "طلب المعلومات الخاصة بالمحل",
  "manager.deletePack": "إلغاء تفعيل باقة",
  "manager.choosePack": "الاشتراك بباقة جديدة",
  "manager.updateDiscount": "تعديل قيمة الخصم الخاصة بالباقة",
  "manager.uploadStory": "رفع صور حالات",
  "manager.deleteStory": "حذف صور حالات",
  "manager.uploadAvatar": "رفع صورة المحل",
  "manager.deleteAvatar": "حذف صورة المحل",
  "store.disableShowInCart": "الظهور في العروض اليومية",
};

export const reverseShow = {
  home: "الرئيسية",
  profile: "الشخصية",
  categories: "الأصناف",
  roles: "الأدوار",
  blocks: "الحظورات",
  packs: "الباقات",
  employees: "الموظفين",
  users: "المستخدمين",
  stores: "المحلات",
  storeInformation: "المحل",
  offers: "العروض",
};
